services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  db:
    image: postgres:17.6-alpine
    container_name: postgresDB
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    restart: always

  config-server:
    image: configserver
    container_name: configserver
    ports:
      - "8888:8888"
    restart: always

  eureka-server:
    image: eurekaserver
    container_name: eurekaserver
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    restart: always

  user-spring-app:
    image: userspringapp
    container_name: userSpringApp
    restart: always
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  email-notification:
    image: emailnotification
    container_name: emailNotification
    restart: always
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - 8099:8099

  gateway:
    image: gateway
    container_name: gateway
    restart: always
    depends_on:
      - user-spring-app
      - email-notification
    ports:
      - 9090:9090