spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./config/{application}/
            - file:./config/eurekaCommonSettingsClient/
            - file:./config/swaggerCommonSettings/
server:
  port: 8888